// tests/theme-switching.test.ts
// Integration tests for theme switching functionality

import { describe, it, expect } from 'vitest';
import { themes, getTheme } from '../src/lib/themes/registry.js';
import { generateThemeVariables, generateSettingsVariables } from '../src/lib/utils/css-vars.js';
import type { ThemeSettings } from '../src/lib/types.js';

// List of all expected themes
const expectedThemeIds = [
	'grove',
	'minimal',
	'night-garden',
	'zine',
	'moodboard',
	'typewriter',
	'solarpunk',
	'cozy-cabin',
	'ocean',
	'wildflower'
];

describe('Theme Switching', () => {
	describe('Theme Retrieval', () => {
		it('should retrieve any theme by ID', () => {
			// Test that getTheme returns correct theme for each ID
			expectedThemeIds.forEach((id) => {
				const theme = getTheme(id);
				expect(theme).toBeDefined();
				expect(theme?.id).toBe(id);
			});
		});

		it('should return undefined for invalid theme ID', () => {
			expect(getTheme('nonexistent')).toBeUndefined();
			expect(getTheme('')).toBeUndefined();
			expect(getTheme('invalid-theme-id')).toBeUndefined();
		});

		it('should list all theme IDs', () => {
			const ids = Object.keys(themes);
			expect(ids).toHaveLength(10);
			expect(ids).toContain('grove');
			expect(ids).toContain('minimal');
			expect(ids).toContain('night-garden');
			expect(ids).toContain('zine');
			expect(ids).toContain('moodboard');
			expect(ids).toContain('typewriter');
			expect(ids).toContain('solarpunk');
			expect(ids).toContain('cozy-cabin');
			expect(ids).toContain('ocean');
			expect(ids).toContain('wildflower');
		});

		it('should retrieve themes with consistent data', () => {
			const groveFromGet = getTheme('grove');
			const groveFromRegistry = themes['grove'];
			expect(groveFromGet).toEqual(groveFromRegistry);
		});
	});

	describe('CSS Variable Generation', () => {
		it('should generate CSS variables for each theme', () => {
			// Test generateThemeVariables works for all themes
			Object.values(themes).forEach((theme) => {
				const cssVars = generateThemeVariables(theme);

				expect(cssVars).toBeTruthy();
				expect(typeof cssVars).toBe('string');
				expect(cssVars).toContain(':root {');

				// Verify all color variables are present
				expect(cssVars).toContain('--color-background:');
				expect(cssVars).toContain('--color-surface:');
				expect(cssVars).toContain('--color-foreground:');
				expect(cssVars).toContain('--color-foreground-muted:');
				expect(cssVars).toContain('--color-accent:');
				expect(cssVars).toContain('--color-border:');

				// Verify font variables are present
				expect(cssVars).toContain('--font-heading:');
				expect(cssVars).toContain('--font-body:');
				expect(cssVars).toContain('--font-mono:');

				// Verify layout variables are present
				expect(cssVars).toContain('--max-width:');

				// Verify spacing variables are present
				expect(cssVars).toContain('--spacing-xs:');
				expect(cssVars).toContain('--spacing-sm:');
				expect(cssVars).toContain('--spacing-md:');
				expect(cssVars).toContain('--spacing-lg:');
				expect(cssVars).toContain('--spacing-xl:');
				expect(cssVars).toContain('--spacing-2xl:');
			});
		});

		it('should generate valid CSS for grove theme', () => {
			const theme = getTheme('grove')!;
			const cssVars = generateThemeVariables(theme);

			expect(cssVars).toContain(`--color-background: ${theme.colors.background};`);
			expect(cssVars).toContain(`--color-accent: ${theme.colors.accent};`);
			expect(cssVars).toContain(`--font-heading: ${theme.fonts.heading};`);
			expect(cssVars).toContain(`--max-width: ${theme.layout.maxWidth};`);
		});

		it('should generate accent color variations', () => {
			const theme = getTheme('minimal')!;
			const cssVars = generateThemeVariables(theme);

			// Check for accent variations generated by color-mix
			expect(cssVars).toContain('--accent-color-light:');
			expect(cssVars).toContain('--accent-color-dark:');
			expect(cssVars).toContain('--accent-color-hover:');
			expect(cssVars).toContain('--accent-color-muted:');
			expect(cssVars).toContain('color-mix');
		});

		it('should generate different spacing values based on layout spacing', () => {
			const compactTheme = Object.values(themes).find((t) => t.layout.spacing === 'compact');
			const comfortableTheme = Object.values(themes).find(
				(t) => t.layout.spacing === 'comfortable'
			);
			const spaciousTheme = Object.values(themes).find((t) => t.layout.spacing === 'spacious');

			if (compactTheme && comfortableTheme && spaciousTheme) {
				const compactVars = generateThemeVariables(compactTheme);
				const comfortableVars = generateThemeVariables(comfortableTheme);
				const spaciousVars = generateThemeVariables(spaciousTheme);

				// Verify different spacing values are generated
				expect(compactVars).not.toBe(comfortableVars);
				expect(comfortableVars).not.toBe(spaciousVars);
			}
		});
	});

	describe('Theme Settings and Overrides', () => {
		it('should apply custom settings over base theme', () => {
			const baseTheme = getTheme('grove')!;
			const settings: ThemeSettings = {
				tenantId: 'test-tenant',
				themeId: 'grove',
				accentColor: '#ff0000',
				customizerEnabled: true
			};

			const cssVars = generateSettingsVariables(settings, baseTheme);

			expect(cssVars).toBeTruthy();
			expect(cssVars).toContain('--color-accent: #ff0000;');
			expect(cssVars).toContain('--color-background:');
		});

		it('should handle accent color override', () => {
			const baseTheme = getTheme('minimal')!;
			const customAccent = '#8b5cf6';
			const settings: ThemeSettings = {
				tenantId: 'test-tenant',
				themeId: 'minimal',
				accentColor: customAccent,
				customizerEnabled: false
			};

			const cssVars = generateSettingsVariables(settings, baseTheme);

			// Accent color should be overridden
			expect(cssVars).toContain(`--color-accent: ${customAccent};`);

			// Accent variations should use the custom color
			expect(cssVars).toContain(customAccent);
			expect(cssVars).toContain('color-mix');
		});

		it('should merge custom colors with base theme', () => {
			const baseTheme = getTheme('night-garden')!;
			const settings: ThemeSettings = {
				tenantId: 'test-tenant',
				themeId: 'night-garden',
				accentColor: baseTheme.colors.accent,
				customizerEnabled: true,
				customColors: {
					background: '#1a1a1a',
					foreground: '#ffffff'
				}
			};

			const cssVars = generateSettingsVariables(settings, baseTheme);

			// Custom colors should be applied
			expect(cssVars).toContain('--color-background: #1a1a1a;');
			expect(cssVars).toContain('--color-foreground: #ffffff;');

			// Non-overridden colors should remain from base theme
			expect(cssVars).toContain(`--color-surface: ${baseTheme.colors.surface};`);
		});

		it('should merge custom typography with base theme', () => {
			const baseTheme = getTheme('typewriter')!;
			const settings: ThemeSettings = {
				tenantId: 'test-tenant',
				themeId: 'typewriter',
				accentColor: baseTheme.colors.accent,
				customizerEnabled: true,
				customTypography: {
					heading: 'Custom Heading Font',
					body: 'Custom Body Font'
				}
			};

			const cssVars = generateSettingsVariables(settings, baseTheme);

			// Custom typography should be applied
			expect(cssVars).toContain('--font-heading: Custom Heading Font;');
			expect(cssVars).toContain('--font-body: Custom Body Font;');

			// Non-overridden font should remain from base theme
			expect(cssVars).toContain(`--font-mono: ${baseTheme.fonts.mono};`);
		});

		it('should merge custom layout with base theme', () => {
			const baseTheme = getTheme('zine')!;
			const settings: ThemeSettings = {
				tenantId: 'test-tenant',
				themeId: 'zine',
				accentColor: baseTheme.colors.accent,
				customizerEnabled: true,
				customLayout: {
					maxWidth: '1400px',
					spacing: 'spacious'
				}
			};

			const cssVars = generateSettingsVariables(settings, baseTheme);

			// Custom layout should be applied
			expect(cssVars).toContain('--max-width: 1400px;');

			// Spacing should reflect the custom value (spacious)
			expect(cssVars).toContain('--spacing-xs:');
		});

		it('should preserve all base theme properties when no overrides', () => {
			const baseTheme = getTheme('ocean')!;
			const settings: ThemeSettings = {
				tenantId: 'test-tenant',
				themeId: 'ocean',
				accentColor: baseTheme.colors.accent,
				customizerEnabled: false
			};

			const cssVars = generateSettingsVariables(settings, baseTheme);

			// All base theme properties should be present
			expect(cssVars).toContain(`--color-background: ${baseTheme.colors.background};`);
			expect(cssVars).toContain(`--color-surface: ${baseTheme.colors.surface};`);
			expect(cssVars).toContain(`--color-foreground: ${baseTheme.colors.foreground};`);
			expect(cssVars).toContain(`--font-heading: ${baseTheme.fonts.heading};`);
			expect(cssVars).toContain(`--font-body: ${baseTheme.fonts.body};`);
			expect(cssVars).toContain(`--max-width: ${baseTheme.layout.maxWidth};`);
		});
	});

	describe('Theme Switching Integration', () => {
		it('should successfully switch between different themes', () => {
			const theme1 = getTheme('grove')!;
			const theme2 = getTheme('minimal')!;

			const vars1 = generateThemeVariables(theme1);
			const vars2 = generateThemeVariables(theme2);

			// Variables should be different for different themes
			expect(vars1).not.toBe(vars2);
			expect(vars1).toContain(theme1.colors.accent);
			expect(vars2).toContain(theme2.colors.accent);
		});

		it('should switch from theme to customized settings', () => {
			const baseTheme = getTheme('wildflower')!;
			const baseVars = generateThemeVariables(baseTheme);

			const settings: ThemeSettings = {
				tenantId: 'test-tenant',
				themeId: 'wildflower',
				accentColor: '#ff00ff',
				customizerEnabled: true,
				customColors: {
					background: '#000000'
				}
			};

			const settingsVars = generateSettingsVariables(settings, baseTheme);

			// Settings should override the base theme
			expect(baseVars).toContain(baseTheme.colors.accent);
			expect(settingsVars).toContain('#ff00ff');
			expect(settingsVars).toContain('--color-background: #000000;');
		});

		it('should handle switching between all 10 themes without errors', () => {
			expectedThemeIds.forEach((id) => {
				const theme = getTheme(id);
				expect(theme).toBeDefined();

				const cssVars = generateThemeVariables(theme!);
				expect(cssVars).toBeTruthy();
				expect(cssVars).toContain(':root {');
			});
		});
	});
});
